### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by Lucxjo** [Lucxjo/Diru#15]
With the addition of Google Translate, the configuration of the bot should be updated.

- [x]  Switch config handler to Viper (if possible) (#16)
- [x]  Allow for only Google Translate or DeepL to be added (#17)
- [ ]  Allow for per-server configuration as to whether gtr or dpl is used by default (#18)
- [ ]  Allow for per-server configuration as to what language is used by default (#18)
- [ ]  Allow for predetermined defaults as to whether gtr or dpl is used by default
