### ISSUE TITLE
Convert project to Discord.TS

### ISSUE THREAD

**Issue by Lucxjo** [Lucxjo/Diru#29]
## Motivation
Diru was originally written as a bot for a server that I'm an admin in, I wrote it in Go to be as small and light on resources as possible. It was also kind of a "let's see what I can do with Go" project. While writing it, I have found how hard to manoeuvre Go can be and that the Discord library that I'm using (Disgord) isn't really ready for production. With this in mind, to go further with this project (and for it's survival), I believe that the bot needs to be ported to Node and TypeScript. The current version (at the point of writing this), will be known as `Diru.Go`, and the newer one will be known as `Diru.Node` when clarity is needed.

## Future plans
Once Diru.Node has full feature parity with Discord.Go, we can get started with the improvements. I want to ensure that the reliance on text commands goes away in favour of application commands (a.k.a slash commands) as well as context menus (where possible).

**`@Diru` commands will be depreciated on 2023-01-28 at 13:00 (UTC)**

## Tasks to complete:
 - PARITY
   - [x] Translation through DeepL (#30)
   - [ ] Translation through Google Translate (#33)
   - [ ] Guild preferences (#34)
   - [ ] Web landing page (for status page) (#35)
 - IMPROVEMENTS
   - [ ] Web API to ensure obfuscation of user information to 3rd party services
